### ISSUE TITLE
pkgdiff is not able to execute abi-compliance-checker correctly

### ISSUE THREAD

**Issue by hobbes1069** [lvc/pkgdiff#20] opened 2015-11-05 18:55 UTC
I have a user trying pkgdiff 1.7.0 but abi-compliance-checker (1.99.13) seems to not like the options being passed to it.

https://bugzilla.redhat.com/show_bug.cgi?id=1277606

**Comment by lvc** [comment] 2015-11-05 21:12
The issue is that the abi-cc tool can only take arguments with suffixes "abi", "abidump" and "dump". But pkgdiff passes "*.txt" files to it. I'll fix this soon.

Thank you.

**Comment by hobbes1069** [comment] 2015-12-09 15:18
Any updates on this issue?

**Comment by aponomarenko** [comment] 2015-12-11 20:35
Fixed in 1.7.1.

Thank you.

**Closed by aponomarenko** 2015-12-11 20:35 UTC
